### ISSUE TITLE
[QUESTION] Generation throughput in my experiment much lower than that reported

### ISSUE THREAD

**Issue by A-LinCui** [bytedance/ShadowKV#1]
**Question**
Hello, it is very nice to see this interesting work.
However, when trying to implement results in Table 4, the throughput using ShadowKV is much lower than that reported.
As shown in the table below, throughput using vanilla KV cache is similar to that reported. But that using ShadowKV is much lower.
| Model | Context (K) | Full Attention (tokens / s) | ShadowKV (tokens / s) | Gain |
|:----:|:----:|:----:|:----:|:----:|
| GLM-4-9B-1M (4 KV heads) | 60 | 223 (12) |  358 (50) | 1.61x |
| GLM-4-9B-1M (4 KV heads) | 122 | 114 (6) | 182 (25) | 1.60 x |
|  Yi-9B-200K (4 KV heads) | 60 | 192.74 (10) | 336.11 (42) | 1.74 x |
|  Yi-9B-200K (4 KV heads) | 122 | 94.83 (5) | 167.24 (21) | 1.76 x |
|  Yi-9B-200K (4 KV heads) | 244 | 43.83 (2) | 75.20 (10) | 1.72 x | 

I wonder whether this is due to environment difference or my implementing mistakes. 

**Environment**
```
Driver: 550.54.14
CUDA: 12.4
Python: 3.10.0
transformers: 4.43.1
torch: 2.3.1
OS: Ubuntu, x86_64, 22.04.2 LTS
Device: A single NVIDIA A100 80GB
```

**Command**
```
python test/e2e.py --model_name "THUDM/glm-4-9b-chat-1m" --datalen "122k"
```

Looking forward to hearing from you.

**Comment by liwenchangbdbz** [comment]
Thanks for being interested in ShadowKV.

Based on your reported numbers, it is highly likely that your is bounded by PCIe. 
ShadowKV offloads and stream in V through PCIe. 

Full attention directly uses GPU DRAM and gets similar numbers, meaning your clock frequency is similar.
ShadowKV gets faster dull attention, meaning the computation part highly likely correct,  
but worse than Table 4, implying your PCIe might be too slow.
Table 4 is measured using A100 SXM4 having PCIe with 31.5GB/s theoretical bandwidth single directional (which is mentioned in Figure 1). 
The practical/measured bandwidth should be at least 24-26 GB/s, single directional.

There might be several reasons that make your PCIe slow, including your mother chipset, lower generation of PCIe, traffic, or using different A100 PCIe card instead of A100 SXM4. 
I will suggest you run a micro-benchmarking testing your PCIe bandwidth or H2D bandwidth to check your PCIe bandwidth.
There is a tuning knob in kernels/copy.cub that can adapt different PCIe to reach a reasonable/practical speed of PCIe. 
However, it won't make your streaming-in V faster than your PCIe physical speed.

**Comment by A-LinCui** [comment]
Thanks for your reply.
By running ``bandwidthTest``, I get the following result.

```
[CUDA Bandwidth Test] - Starting...
Running on...

  Device 0: NVIDIA A100 80GB PCIe
  Quick Mode

  Host to Device Bandwidth, 1 Device(s)
  PINNED Memory Transfers
    Transfer Size (Bytes)        Bandwidth(MB/s)
    33554432                     7831.1

  Device to Host Bandwidth, 1 Device(s)
  PINNED Memory Transfers
    Transfer Size (Bytes)        Bandwidth(MB/s)
    33554432                     9095.4

  Device to Device Bandwidth, 1 Device(s)
  PINNED Memory Transfers
    Transfer Size (Bytes)        Bandwidth(MB/s)
    33554432                     1416320.9

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
```

I have to say that I am not a specialist in this field.
Does it mean my bandwidth is too small by comparing 7GB/s or 9GB/s with 24-26GB/s?

**Comment by preminstrel** [comment]
Most of the servers now are using PCIe 4.0, maxing out at 32 GB/s in a 16-lane slot.

**Comment by wenlei-bao** [comment]
@A-LinCui  We suggest that you use below script (lstopo command) to check your PCIE topo connection on your machine.
```
# install dependencies
sudo apt update -y && sudo apt install zsh tmux file libnet-ifconfig-wrapper-perl/oldstable -y
sudo apt install graphviz hwloc -y

env

WORKDIR=/your/work/path
mkdir -p $WORKDIR
sudo chown -R root:root ${WORKDIR} 

pushd ${WORKDIR}
# mkdir on mounts
lshw -numeric -class display &> gpu-info
lstopo-no-graphics  --of txt > lstopo.txt
hwloc-ls hwloc.png
nvidia-smi -q > nvidia_smi_q.txt
```

**Comment by liwenchangbdbz** [comment]
> @A-LinCui We suggest that you use below script (lstopo command) to check your PCIE topo connection on your machine.
> 
> ```
> # install dependencies
> sudo apt install graphviz hwloc -y
> 
> env
> 
> WORKDIR=/your/work/path
> mkdir -p $WORKDIR
> sudo chown -R root:root ${WORKDIR} 
> 
> pushd ${WORKDIR}
> # mkdir on mounts
> lshw -numeric -class display &> gpu-info
> lstopo-no-graphics  --of txt > lstopo.txt
> hwloc-ls hwloc.png
> nvidia-smi -q > nvidia_smi_q.txt
> ```

Let me mention slightly more about the above script.

In your situation, slower PCIe could come from 1) lower generation of PCIe of your mother board or 2) plugging-in a wrong PCIe slot with fewer lanes. 
The latter could be more possible, since PCIe gen4 has been there for a while.
The above script is helping detect your PCIe topology and show how many lanes for each PCIe card in your system.
If the PCIe slot is wrong, you can simply re-plug your A100 to a right one with 16 lanes.

For detecting PCIe generation, you can use Linux commands like **lspci** or **dmidecode**.
If it happened to be the first case, you might want to replace your mother board to a better one that can really fully utilize A100 well.

**Comment by A-LinCui** [comment]
Thanks. I get it. I just find I'm using PCIe gen3.
